creating a variables with python data types


In [ ]:
a ="apple" #string
b=1 #int
c= 1.2 #float
d=2+3j #complex
e = {1,2,"hgds",2.5} #set
f = [1,2,"hgds",2.5] #list
g= (1,2,"hgds",2.5) #tuple
h = {"name":"ram","roll":20} #dictionaries
print(a,b,c,d,e,f,g,h)

apple 1 1.2 (2+3j) {1, 2, 2.5, 'hgds'} [1, 2, 'hgds', 2.5] (1, 2, 'hgds', 2.5) {'name': 'ram', 'roll': 20}


conditional statements:
1.if
2.if else
3.elif
4.nasted if

In [ ]:
a=20
b=30
if a>b:
  print("true")
else:
  print("false")


false


In [ ]:
a=30
b=20
if a<b:
  print("a<b")
if a>b:
  print("a>b")


a>b


In [ ]:
a="hdhe"
b="bebbe"
if a==b:
  print("yes")
elif b==a:
  print("yes")
else:
  print("no")

no


In [ ]:
a=200
b=300
c=600
if a<b:
  if a<c:
    print("a<b and c")
  else:
    print("a>b")
else:
  print("a>b")


a<b and c


Short hand condition and

In [ ]:
print("yes") if 29>9 else print("no")

yes


1.break
2.continue
3.pass

In [ ]:
for i in range(1,11):
  if i == 3:
    break
  print(i)



1
2


In [ ]:
for i in range(1,11):
  if i ==8:
    continue
  print(i)


1
2
3
4
5
6
7
9
10


looping stmt
1.**while**
2.**for**

In [ ]:
a=1
while a<6:
  print(a)
  a+=1

1
2
3
4
5


In [ ]:
f = ["ca","ba","app"]
for i in f:
  print(i)

ca
ba
app


In [ ]:
a= [1,2,3]
b= [4,5,6]
for i in a:
  for j in b:
    print(i,j)
  print()

1 4
1 5
1 6

2 4
2 5
2 6

3 4
3 5
3 6



**numpy**

**empty**

In [ ]:
import numpy as np
arr = np.empty((2,3))
print(arr)

[[4.82686681e-310 0.00000000e+000 2.05833592e-312]
 [6.79038654e-313 2.14321575e-312 2.27053550e-312]]


**empty_likes**

In [ ]:
import numpy as np
arr = np.empty_like([[1,2,3],[4,5,6]])
print(arr)

a = np.array([[1., 2., 3.],[4.,5.,6.]])
c = np.empty_like(a)
print(c)

[[4602721353169127634 4599746475415270122 4602721353169127634]
 [4616227022951663505 4617838748668308721 4599746475415270122]]
[[0.50472222 0.33722222 0.50472222]
 [4.03322222 5.46472222 0.33722222]]


**1.full**
**2.full_like**

In [ ]:
import numpy as np
full = np.full((2,3),0)+1
print(full)


#full_like
arr = np.array([[1,2],[3,4]] ,dtype = 'i2')
full1 = np.full_like(arr,5)+1
print(full1)


[[1 1 1]
 [1 1 1]]
[[6 6]
 [6 6]]


**repeat**

In [ ]:
arr= [[0,1,2],[3,4,5]]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [ ]:
arr = [[0,1,2],[3,4,5]]
print(np.repeat(arr, 3,axis = 1))

[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


**tile**

In [ ]:
arr = [[0,1,2]]
print(np.tile(arr,3))

print(np.tile(arr,(3,3)))

[[0 1 2 0 1 2 0 1 2]]
[[0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]]


**matrix of given size**
**-> eye**

In [ ]:
#identify matrix of given size
matrix = np.eye(5,dtype = 'i2')
print(matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
ma = np.eye(5,k=-3,dtype = 'i2')
print(ma)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]]


**Diagonal**

In [ ]:
arr = np.diag([1,2,3,4,5,6])
print(arr)

[[2 1 1 1 1 1]
 [1 3 1 1 1 1]
 [1 1 4 1 1 1]
 [1 1 1 5 1 1]
 [1 1 1 1 6 1]
 [1 1 1 1 1 7]]


**information about array**

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.info(arr))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x57721f67e5d0
byteorder:  little
byteswap:  False
type: int64
None


**reshape**
**to convert into matrix**

In [ ]:
arr = np.arange(16).reshape(4,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


**transpose**

**row to column and column to row**

In [ ]:
print(arr.T)

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


**fixed to random values by using random.seed()**

In [ ]:
np.random.seed(123)
arr = np.random.rand(5)
print(arr)

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]


In [ ]:
np.random.seed(123)
print(arr)

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]


In [ ]:
print(np.random.randn(3,3))

[[-1.61930007 -1.11396442 -0.44744072]
 [ 1.66840161 -0.14337247 -0.6191909 ]
 [-0.76943347  0.57674602  0.12652592]]


In [ ]:
print(np.random.randint(1,10,(3,3),'i2'))

[[7 2 6]
 [7 2 3]
 [2 1 9]]


**types for random**

In [ ]:
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.46426806 0.56843069 0.30254945 0.49730879 0.68326291 0.91669867
 0.10892895 0.49549179 0.23283593 0.43686066]
[0.75154299 0.48089213 0.79772841 0.28270293 0.43341824 0.00975735
 0.34079598 0.68927201 0.86936929 0.26780382]
[0.45674792 0.26828131 0.8370528  0.27051466 0.53006201 0.17537266
 0.31496645 0.8911091  0.18033628 0.4943162 ]
[0.2122981  0.52087687 0.16009994 0.9190568  0.99428992 0.47704756
 0.30988351 0.50720432 0.2807932  0.76383669]


In [ ]:
print(np.random.choice(range(3),10,replace = True,p=[0.1,0.5,0.4]))

[2 1 1 1 2 1 2 2 2 1]


In [ ]:
print(np.random.choice(5,10))
print("\n")
print(np.random.choice([1,2,3],10))

[3 0 0 4 4 0 0 4 1 2]


[2 2 2 1 2 1 3 3 1 1]


In [ ]:
arr = np.arange(10)
print(arr)
np.random.shuffle(arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[9 8 5 0 7 4 2 1 3 6]


**indexing and slicing**

**->** **boolean slicing**

In [ ]:
arr1 = np.arange(25).reshape((5,5))
bools = np.array([True,True,False,True,False])
print(arr1[bools])
#print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


**negative conditions**

In [ ]:
print(arr1[~bools])

[[10 11 12 13 14]
 [20 21 22 23 24]]


**pandas**

In [ ]:
import pandas as pd
data = [10,20,30,40]
ser = pd.Series(data)
ser

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
data = {'a':1,"b":2,"c":3}
ser = pd.Series(data)
ser

a    1
b    2
c    3
dtype: int64

In [ ]:
values = [100,200,300]
index = ["x","y","z"]
ser = pd.Series(values,index = index)
ser

x    100
y    200
z    300
dtype: int64

In [ ]:
sc = 5
ser = pd.Series(6,index = [1,2,3,4])
ser

1    6
2    6
3    6
4    6
dtype: int64

In [ ]:
data = [1,"apple",0.56,True]
ser =pd.Series(data)
ser

0        1
1    apple
2     0.56
3     True
dtype: object

In [ ]:
dates = pd.date_range('2024-09-2',periods = 3)
values = [100,200,300]
ser = pd.Series(values,index = dates)
ser

2024-09-02    100
2024-09-03    200
2024-09-04    300
Freq: D, dtype: int64

In [ ]:
data = [complex(1,2),complex(3,4),complex(5,6)]
ser =pd.Series(data)
ser

0    1.0+2.0j
1    3.0+4.0j
2    5.0+6.0j
dtype: complex128

In [ ]:
data = {
    'name' : ['allu','balu','bob'],
    'age' : ['25','29','30'],
    'city':['newyork','hyd','bangl']

}
index = ["a","b","c"]
df = pd.DataFrame(data,index =index)
df

name age     city
a  allu  25  newyork
b  balu  29      hyd
c   bob  30    bangl

In [ ]:
data = [
    ['alice',25,'newyork'],
    ['bob',29,'hyd'],
    ['balu',30,'bang']
]
columns = ["name","age","city"]
df = pd.DataFrame(data,columns = columns)
df

name  age     city
0  alice   25  newyork
1    bob   29      hyd
2   balu   30     bang

In [ ]:
import numpy as np
import pandas as pd
data=np.array([
    [1,"jai",25],
    [2,'iaj',26],
    [3,'aij',27]
])
flow = ["id",'name',"age"]
df = pd.DataFrame(data,columns = flow)
df

id name age
0  1  jai  25
1  2  iaj  26
2  3  aij  27

In [ ]:
s1 = pd.Series([1,2,3],name ="id")
s2 = pd.Series(["jai","aij","iaj"],name = "names")
s3 = pd.Series([25,26,27],name = "age")
#combines all series into dataframes
df = pd.concat([s1,s2,s3],axis =1)
df

id names  age
0   1   jai   25
1   2   aij   26
2   3   iaj   27

In [ ]:
df = pd.DataFrame(columns = ["name","age","city"])
num_rows = pd.DataFrame(([{'name':'a',
                           'age':20,
                           'city':'hyd'},
                          {'name':'b',
                           'age':21,
                           'city':'bang'

                          }]))
df = pd.concat([df,num_rows],ignore_index = False)
df

name age  city
0    a  20   hyd
1    b  21  bang

**multiindex**

In [ ]:
#creating a dataframe with mutiindex
import pandas as pd
index = pd.MultiIndex.from_tuples([
    ('A','first'),
    ('A',"second"),
    ('B',"first"),
    ('B',"second")
],names = ["category","subcatagory"])
data = {
    "values" : [1,2,3,4]
}
df = pd.DataFrame(data,index = index)
df

values
category subcatagory        
A        first             1
         second            2
B        first             3
         second            4

**data frame with random data**

In [ ]:
import numpy as np
import pandas as pd
data = np.random.rand(3,3)
column = ["a","b","c"]
df = pd.DataFrame(data,columns = column)
df

a         b         c
0  0.118896  0.705568  0.152949
1  0.093357  0.225074  0.770082
2  0.095929  0.543258  0.918280

**dataframe with sepecific data type**

In [ ]:
data = {
    "integer" : [1,2,3],
    "float": [1.1,2.2,3.3],
    "string" : ["aa","a","aaa"]
}
df = pd.DataFrame(data)
df = df.astype({"integer":'int32','float':'float64',"string":"str"})
#print(df.dtype)
df

integer  float string
0        1    1.1     aa
1        2    2.2      a
2        3    3.3    aaa

**important**

**creating dataframe from a sql query**

In [ ]:
import sqlite3
conn = sqlite3.connect(':memory:')
conn.execute('''
CREATE TABLE people(
  id integer primary key,
  name text,
  age integer
)''')
conn.execute('''
INSERT INTO people(name,age)
VALUES ('alice',20),
('bob',30)
''')
query = 'select * from people'
df  = pd.read_sql_query(query,conn)
df

id   name  age
0   1  alice   20
1   2    bob   30

In [ ]:
import sqlite3
import pandas as pd
conn =sqlite3.connect(":memory:")
conn.execute('''
CREATE TABLE people3(
  id integer primary key,
  name text,
  age integer
)''')
conn.execute('''
INSERT INTO people3(name, age)
VALUES('san',21),
('shiv',27)''')
query = 'select * from people3'
df =pd.read_sql_query(query,conn)
df.index.name = 'sn'
df.index = ["->","->"]
df


id  name  age
->   1   san   21
->   2  shiv   27

***csv files***

In [ ]:
#for  importing dataset from the drive
'''from google.colab import drive
drive.mount('copy path')'''


# to read data
'''df = pd.read_csv('copy path')
df'''
#showes output


In [ ]:
import pandas as pd
df = pd.read_('/content/drive/MyDrive/transaction.xlsx')
df

UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 15-16: invalid continuation byte

In [ ]:
pip install pandas openpyxl

status  card_present_flag bpay_biller_code         account  \
0      authorized                1.0              NaN  ACC-1598451071   
1      authorized                0.0              NaN  ACC-1598451071   
2      authorized                1.0              NaN  ACC-1222300524   
3      authorized                1.0              NaN  ACC-1037050564   
4      authorized                1.0              NaN  ACC-1598451071   
...           ...                ...              ...             ...   
12038  authorized                0.0              NaN  ACC-3021093232   
12039  authorized                1.0              NaN  ACC-1608363396   
12040  authorized                1.0              NaN  ACC-3827517394   
12041  authorized                1.0              NaN  ACC-2920611728   
12042  authorized                1.0              NaN  ACC-1443681913   

      currency       long_lat txn_description  \
0          AUD  153.41 -27.95             POS   
1          AUD  153.41 -27.95       SALES-POS   
2          AUD  151.23 -33.94             POS   
3          AUD  153.10 -27.66       SALES-POS   
4          AUD  153.41 -27.95       SALES-POS   
...        ...            ...             ...   
12038      AUD  149.83 -29.47             POS   
12039      AUD  151.22 -33.87       SALES-POS   
12040      AUD  151.12 -33.89             POS   
12041      AUD  144.96 -37.76       SALES-POS   
12042      AUD  150.92 -33.77       SALES-POS   

                                merchant_id  merchant_code first_name  ...  \
0      81c48296-73be-44a7-befa-d053f48ce7cd            NaN      Diana  ...   
1      830a451c-316e-4a6a-bf25-e37caedca49e            NaN      Diana  ...   
2      835c231d-8cdf-4e96-859d-e9d571760cf0            NaN    Michael  ...   
3      48514682-c78a-4a88-b0da-2d6302e64673            NaN     Rhonda  ...   
4      b4e02c10-0852-4273-b8fd-7b3395e32eb0            NaN      Diana  ...   
...                                     ...            ...        ...  ...   
12038  32aa73dc-b7c2-4161-b14d-6271b96ce792            NaN    Melissa  ...   
12039  296a0500-8552-48ac-ac81-ec37065b568e            NaN     Robert  ...   
12040  e5975ab4-08f7-4725-a369-24cc0e35ed6e            NaN      Craig  ...   
12041  af49051a-591d-4b08-bd3c-27730b70ed37            NaN      Tyler  ...   
12042  f31f4b14-2040-40ec-a120-b141bb274cbd            NaN       Ryan  ...   

       age merchant_suburb merchant_state                    extraction  \
0       26         Ashmore            QLD  2018-08-01T01:01:15.000+0000   
1       26          Sydney            NSW  2018-08-01T01:13:45.000+0000   
2       38          Sydney            NSW  2018-08-01T01:26:15.000+0000   
3       40         Buderim            QLD  2018-08-01T01:38:45.000+0000   
4       26   Mermaid Beach            QLD  2018-08-01T01:51:15.000+0000   
...    ...             ...            ...                           ...   
12038   30        Ringwood            VIC  2018-10-31T23:09:06.000+0000   
12039   20          Casula            NSW  2018-10-31T23:21:46.000+0000   
12040   28      Kings Park            NSW  2018-10-31T23:34:25.000+0000   
12041   69        Oakleigh            VIC  2018-10-31T23:47:05.000+0000   
12042   31          Mascot            NSW  2018-10-31T23:59:44.000+0000   

      amount                    transaction_id    country     customer_id  \
0      16.25  a623070bfead4541a6b0fff8a09e706c  Australia  CUS-2487424745   
1      14.19  13270a2a902145da9db4c951e04b51b9  Australia  CUS-2487424745   
2       6.42  feb79e7ecd7048a5a36ec889d1a94270  Australia  CUS-2142601169   
3      40.90  2698170da3704fd981b15e64a006079e  Australia  CUS-1614226872   
4       3.25  329adf79878c4cf0aeb4188b4691c266  Australia  CUS-2487424745   
...      ...                               ...        ...             ...   
12038   9.79  f2e3e695c2ee4c50a4c8747f852cbe2e  Australia    CUS-55310383   
12039  63.87  56e147e5485f4683b9076fcaaed76640  Australia  CUS-2688605418   
12040  43.96  

In [ ]:
df.head()

status  card_present_flag bpay_biller_code         account currency  \
0  authorized                1.0              NaN  ACC-1598451071      AUD   
1  authorized                0.0              NaN  ACC-1598451071      AUD   
2  authorized                1.0              NaN  ACC-1222300524      AUD   
3  authorized                1.0              NaN  ACC-1037050564      AUD   
4  authorized                1.0              NaN  ACC-1598451071      AUD   

        long_lat txn_description                           merchant_id  \
0  153.41 -27.95             POS  81c48296-73be-44a7-befa-d053f48ce7cd   
1  153.41 -27.95       SALES-POS  830a451c-316e-4a6a-bf25-e37caedca49e   
2  151.23 -33.94             POS  835c231d-8cdf-4e96-859d-e9d571760cf0   
3  153.10 -27.66       SALES-POS  48514682-c78a-4a88-b0da-2d6302e64673   
4  153.41 -27.95       SALES-POS  b4e02c10-0852-4273-b8fd-7b3395e32eb0   

   merchant_code first_name  ...  age merchant_suburb merchant_state  \
0            NaN      Diana  ...   26         Ashmore            QLD   
1            NaN      Diana  ...   26          Sydney            NSW   
2            NaN    Michael  ...   38          Sydney            NSW   
3            NaN     Rhonda  ...   40         Buderim            QLD   
4            NaN      Diana  ...   26   Mermaid Beach            QLD   

                     extraction amount                    transaction_id  \
0  2018-08-01T01:01:15.000+0000  16.25  a623070bfead4541a6b0fff8a09e706c   
1  2018-08-01T01:13:45.000+0000  14.19  13270a2a902145da9db4c951e04b51b9   
2  2018-08-01T01:26:15.000+0000   6.42  feb79e7ecd7048a5a36ec889d1a94270   
3  2018-08-01T01:38:45.000+0000  40.90  2698170da3704fd981b15e64a006079e   
4  2018-08-01T01:51:15.000+0000   3.25  329adf79878c4cf0aeb4188b4691c266   

     country     customer_id merchant_long_lat movement  
0  Australia  CUS-2487424745     153.38 -27.99    debit  
1  Australia  CUS-2487424745     151.21 -33.87    debit  
2  Australia  CUS-2142601169     151.21 -33.87    debit  
3  Australia  CUS-1614226872     153.05 -26.68    debit  
4  Australia  CUS-2487424745     153.44 -28.06    debit  

[5 rows x 23 columns]

In [ ]:
df.tail()

status  card_present_flag bpay_biller_code         account  \
12038  authorized                0.0              NaN  ACC-3021093232   
12039  authorized                1.0              NaN  ACC-1608363396   
12040  authorized                1.0              NaN  ACC-3827517394   
12041  authorized                1.0              NaN  ACC-2920611728   
12042  authorized                1.0              NaN  ACC-1443681913   

      currency       long_lat txn_description  \
12038      AUD  149.83 -29.47             POS   
12039      AUD  151.22 -33.87       SALES-POS   
12040      AUD  151.12 -33.89             POS   
12041      AUD  144.96 -37.76       SALES-POS   
12042      AUD  150.92 -33.77       SALES-POS   

                                merchant_id  merchant_code first_name  ...  \
12038  32aa73dc-b7c2-4161-b14d-6271b96ce792            NaN    Melissa  ...   
12039  296a0500-8552-48ac-ac81-ec37065b568e            NaN     Robert  ...   
12040  e5975ab4-08f7-4725-a369-24cc0e35ed6e            NaN      Craig  ...   
12041  af49051a-591d-4b08-bd3c-27730b70ed37            NaN      Tyler  ...   
12042  f31f4b14-2040-40ec-a120-b141bb274cbd            NaN       Ryan  ...   

       age merchant_suburb merchant_state                    extraction  \
12038   30        Ringwood            VIC  2018-10-31T23:09:06.000+0000   
12039   20          Casula            NSW  2018-10-31T23:21:46.000+0000   
12040   28      Kings Park            NSW  2018-10-31T23:34:25.000+0000   
12041   69        Oakleigh            VIC  2018-10-31T23:47:05.000+0000   
12042   31          Mascot            NSW  2018-10-31T23:59:44.000+0000   

      amount                    transaction_id    country     customer_id  \
12038   9.79  f2e3e695c2ee4c50a4c8747f852cbe2e  Australia    CUS-55310383   
12039  63.87  56e147e5485f4683b9076fcaaed76640  Australia  CUS-2688605418   
12040  43.96  2fdd4681827343f6af2e6519644a684a  Australia  CUS-2663907001   
12041  30.77  74aa9cd7e4af4c6d9cd7dbd28e9aedc9  Australia  CUS-1388323263   
12042  22.36  6d5218e04e8040b9996850ce11a19426  Australia  CUS-3129499595   

      merchant_long_lat movement  
12038     145.23 -37.81    debit  
12039     150.88 -33.96    debit  
12040     150.92 -33.74    debit  
12041     145.09 -37.91    debit  
12042     151.19 -33.93    debit  

[5 rows x 23 columns]

In [ ]:
df.shape

(12043, 23)

In [ ]:
df.size

276989

In [ ]:
df.sample()

status  card_present_flag bpay_biller_code         account  \
11428  authorized                0.0              NaN  ACC-1516130869   

      currency       long_lat txn_description  \
11428      AUD  130.84 -12.45             POS   

                                merchant_id  merchant_code first_name  ...  \
11428  44e05260-47f6-4a92-855a-6c3e0d6084d2            NaN    Jessica  ...   

       age merchant_suburb merchant_state                    extraction  \
11428   21     Darwin City             NT  2018-10-26T23:59:36.000+0000   

      amount                    transaction_id    country    customer_id  \
11428   8.61  7ffc67cf38c74e658cce6ee4360a528e  Australia  CUS-325142416   

      merchant_long_lat movement  
11428     130.85 -12.46    debit  

[1 rows x 23 columns]

In [ ]:
df.columns

Index(['status', 'card_present_flag', 'bpay_biller_code', 'account',
       'currency', 'long_lat', 'txn_description', 'merchant_id',
       'merchant_code', 'first_name', 'balance', 'date', 'gender', 'age',
       'merchant_suburb', 'merchant_state', 'extraction', 'amount',
       'transaction_id', 'country', 'customer_id', 'merchant_long_lat',
       'movement'],
      dtype='object')

**imputings**

In [ ]:
import pandas as pd
data = {
    'A': [1, 2, None, 4],
    'B': [None, 5, None, 7],
    'C': [9, None, 11, None]
}

df = pd.DataFrame(data)
df


A    B     C
0  1.0  NaN   9.0
1  2.0  5.0   NaN
2  NaN  NaN  11.0
3  4.0  7.0   NaN

In [ ]:
df.isnull().sum()

A    1
B    2
C    2
dtype: int64

In [ ]:
new_data =df.copy()
new_data

A    B     C
0  1.0  NaN   9.0
1  2.0  5.0   NaN
2  NaN  NaN  11.0
3  4.0  7.0   NaN

In [ ]:
from sklearn.impute import SimpleImputer
mean_imputer =SimpleImputer(strategy='mean')
new_data.iloc[:,:] = mean_imputer.fit_transform(new_data)

In [ ]:
new_data

A    B     C
0  1.0  5.0   9.0
1  2.0  5.0   9.0
2  1.0  5.0  11.0
3  4.0  7.0   9.0

In [ ]:
new_data.isnull().sum()

A    1
B    2
C    2
dtype: int64

**imputing with maual given dataset**

In [ ]:
#filling a constant value of a paticular column
new_data['A'].fillna('A',inplace=True)

In [ ]:
new_data

A    B     C
0  1.0  4.0   9.0
1  2.0  5.0   NaN
2    A  4.0  11.0
3  4.0  7.0   NaN

In [ ]:
#filling a constant value of a paticular column
new_data['B'].fillna(4,inplace=True)

In [ ]:
new_data

A    B     C
0  1.0  4.0   9.0
1  2.0  5.0   NaN
2    A  4.0  11.0
3  4.0  7.0   NaN

In [ ]:
#filling with a mean value of a particular colummn
new_data['C'].fillna(new_data['C'].mode(),inplace =True)

In [ ]:
new_data

A    B     C
0  1.0  4.0   9.0
1  2.0  5.0  10.0
2    A  4.0  11.0
3  4.0  7.0  10.0

**forward filling**

In [ ]:
new_data.fillna(method ='ffill',inplace =True)
new_data['A'][0:4]

<ipython-input-45-f3318a3c0ef2>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_data.fillna(method ='ffill',inplace =True)


0    1.0
1    2.0
2    2.0
3    4.0
Name: A, dtype: float64

In [ ]:
new_data

A    B     C
0  1.0  5.0   9.0
1  2.0  5.0   9.0
2  2.0  5.0  11.0
3  4.0  7.0  11.0

**backward filling**

In [ ]:
new_data.fillna(method ='bfill',inplace =True)
new_data['B'][0:4]

<ipython-input-44-9f6f0e281ec1>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_data.fillna(method ='bfill',inplace =True)


0    5.0
1    5.0
2    5.0
3    7.0
Name: B, dtype: float64

**interpolation**

In [ ]:
new_data.interpolate(limit_direction="both",inplace =True)
new_data['C'][0:4]

0     9.0
1     9.0
2    11.0
3    11.0
Name: C, dtype: float64